import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Canvas } from "@react-three/fiber";
import { Stars } from "../components/Stars";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Kosuke Suzuki&apos;s Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Canvas camera={{ position: [0, 0, 1] }}>
          <Stars />
        </Canvas>
      </main>
    </div>
  );
}
